name: Create Archive
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Pull latest and remove old file from repo
      run: |
        git config --global user.name "bruh"
        git config --global user.email "bruh@gmail.com"
        git config pull.rebase false
        git pull
        git checkout output
        
        rm -f release.zip
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'release.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - name: Push changes to remote
      run: |
        git add -A
        git commit -m "new pack"
        git push --force